export enum ERROR {
    SERVER_ERROR = "خطایی در سرور رخ داده است!",
    USER_EXIST = "این کاربر از قبل وجود دارد!",
    EMAIL_EXIST = "این ایمیل از قبل ثبت شده است!",
    CANT_FIND_USER = "کاربر یافت نشد!",
    CANT_FIND_HANDLER = "مدیر یافت نشد!",
    CANT_FIND_BLog = "وبلاگ یافت نشد!",
    CANT_FIND_TESTIMONIALS = "نظر یافت نشد!",
    CANT_FIND_PRODUCT = "محصول یافت نشد!",
    INVALID_DATA = "لطفاً داده معتبر وارد کنید!",
    INVALID_EMAIL = "لطفاً ایمیل معتبر وارد کنید!",
    WRONG_PASSWORD = "ایمیل یا رمز عبور اشتباه است!",
    PROBLEM = "مشکلی رخ داده است!",
    NO_USER = "هیچ کاربری یافت نشد!",
    ACCESS_DENIED = "دسترسی غیرمجاز!",
    LOGIN = "لطفاً ابتدا وارد شوید!",
    REQUIRED_FIELD = "پر کردن این فیلد الزامی است.",
    REQUIRED_NAME = "نام برای ثبت‌نام الزامی است.",
    INVALID_EMAIL_FORMAT = "فرمت ایمیل معتبر نیست.",
    NAME_ATLEAST = "نام باید حداقل ۳ کاراکتر باشد.",
    LASTNAME_ATLEAST = "نام خانوادگی باید حداقل ۳ کاراکتر باشد.",
    PASSWORD_ATLEAST = "رمز عبور باید حداقل ۶ کاراکتر باشد.",
    PHONE_ATLEAST = "شماره تلفن باید ۱۱ رقم باشد.",
    PASSWORD_DONT_MACH = "رمزهای عبور مطابقت ندارند.",
    RESET_LINK_EXPIRED = "لینک بازیابی منقضی شده است. لطفاً دوباره درخواست دهید.",
    INVALID_TOKEN = "توکن نامعتبر است. لطفاً دوباره تلاش کنید.",
    OTP_REQUIRED = "کد تأیید الزامی است!",
    UNAUTHORIZED = "شما اجازه ویرایش این کاربر را ندارید.",
    ALREADY_PROMOTED = "این کاربر قبلاً به این سطح ارتقا یافته است.",
    CANT_FIND_FAQ = "سؤال یافت نشد!",
    INVALID_FORMAT = "فرمت فایل نامعتبر است."
}

export enum MESSAGE {
    NEW_USER = "کاربر با موفقیت ایجاد شد!",
    NEW_BLOG_TESTIMONIALS = "نظر با موفقیت اضافه شد!",
    NEW_BLOG_TESTIMONIALS_REPLY = "پاسخ نظر با موفقیت اضافه شد!",
    USER_DELETE = "کاربر با موفقیت حذف شد!",
    PRODUCT_DELETE = "محصول با موفقیت حذف شد!",
    PASSWORD_RESET_EMAIL = "ایمیل بازیابی رمز عبور با موفقیت ارسال شد.",
    PASSWORD_RESET = "رمز عبور با موفقیت تغییر یافت.",
    VALID_TOKEN = "توکن معتبر است. می‌توانید رمز عبور را تغییر دهید.",
    PROFILE_EDIT = "پروفایل شما با موفقیت ویرایش شد.",
    NEW_ADMIN = "مدیر جدید با موفقیت ارتقا یافت.",
    NEW_BLOG = "وبلاگ با موفقیت ایجاد شد.",
    BLOG_DELETED = "وبلاگ با موفقیت حذف شد.",
    BLOG_PUBLISHED = "وبلاگ با موفقیت منتشر شد.",
    Blog_REJECTED = "وبلاگ با موفقیت رد شد.",
    FAQ_DELETE = "سؤال با موفقیت حذف شد!",
    FAQ_EDIT = "سؤال با موفقیت ویرایش شد!",
    NEW_FAQ = "سؤال جدید با موفقیت اضافه شد!",
    NEW_PRODUCT = "محصول جدید با موفقیت اضافه شد!"
}